# Default values for auth-microservice-auth0.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.freebytech.com/k8s-tests/auth-microservice-auth0
  tag: "latest"
  pullPolicy: Always
  imagePullSecrets: "freebytech-regcred"
env:
  - name: SANDBOXAPP__ENVIRONMENTNAME
    valueFrom:
      secretKeyRef:
        name: standard-env-secrets
        key: ENVIRONMENT_NAME
  - name: SANDBOXAPP__EXTERNALDNSNAME
    valueFrom:
      secretKeyRef:
        name: sandboxapps-env-secrets
        key: SANDBOXAPPS_DNS_NAME
  - name: AUTH0__DOMAIN
    valueFrom:
      secretKeyRef:
        name: sts-env-secrets
        key: AUTH0_DOMAIN
  - name: AUTH0__CLIENTID
    valueFrom:
      secretKeyRef:
        name: sts-env-secrets
        key: AUTH0_CLIENTID
  - name: AUTH0__CLIENTSECRET
    valueFrom:
      secretKeyRef:
        name: sts-env-secrets
        key: AUTH0_CLIENTSECRET
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000
  internalPort: 80

ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    certmanager.k8s.io/cluster-issuer: letsencrypt-production-issuer
    kubernetes.io/tls-acme: "true"
  paths: 
    - /login
  hosts:
    - sandboxapps.ddns.net
  tls:
    - secretName: apps-dyndns-tls
      hosts:
        - sandboxapps.ddns.net

virtualService:
  enabled: true
  gateways: 
    - istio-system/sandboxapps-dyndns-gateway
  hosts: 
    - sandboxapps.ddns.net
  uriPrefixes:
    - /login/

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
