apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-microservice-auth0.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "auth-microservice-auth0.name" . }}
    helm.sh/chart: {{ include "auth-microservice-auth0.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    appNamespace: {{ .Release.Namespace }}
    app: {{ include "mui-test-app1.name" . }}
    version: {{ .Values.image.tag }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "auth-microservice-auth0.name" . }}
    version: {{ .Values.image.tag }}
