{{- if .Values.virtualService.enabled -}}
{{- $fullName := include "auth-microservice-auth0.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "auth-microservice-auth0.name" . }}
    helm.sh/chart: {{ include "auth-microservice-auth0.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
{{- if .Values.virtualService.hosts }}
  hosts:
  {{- range .Values.virtualService.hosts }}
    - {{ . }}
  {{- end }}
{{- end }}
{{- if .Values.virtualService.gateways }}
  gateways:
  {{- range .Values.virtualService.gateways }}
    - {{ . }}
  {{- end }}
{{- end }}
  http:
  - match:
  {{- range .Values.virtualService.uriPrefixes }}
    - uri:
        prefix: {{ . | quote }}
  {{- end }}
    route:
    - destination:
        host: {{ $fullName }}
        port:
          number: {{ .Values.service.port }}
{{- end }}